from __future__ import annotations

from llm_provider_router.adapters.base import NormalizedStream
from llm_provider_router.config import ApiProtocol, ProviderConfig
from llm_provider_router.errors import (
    ConfigError,
    DuplicateCallVariantProtocolError,
    ErrorCategory,
    InvalidOperationArgumentsError,
    MissingApiKeyError,
    MixedCallTypeError,
    ModelArgumentConflictError,
    NoEligibleProvidersError,
    NoProvidersConfiguredError,
    NygenRouterError,
    ProviderConnectionError,
    ProviderError,
    ProviderHTTPError,
    ProviderResponsesError,
    ProviderSDKNotInstalledError,
    ProviderStreamInterruptedError,
    ProviderTimeoutError,
    RouterClosedError,
    RouterExhaustedError,
    UnsupportedOperationError,
    UnsupportedProtocolError,
)
from llm_provider_router.filters import filter_eligible_providers
from llm_provider_router.health import HealthConfig, ProviderHealthReport
from llm_provider_router.metrics import MetricsEvent
from llm_provider_router.policies import (
    HistoryScope,
    Policy,
    RoundRobinPolicy,
    RoutingContext,
    ScoreBasedPolicy,
    StickyRoutingPolicy,
)
from llm_provider_router.retry import (
    RetryContext,
    RetryPolicy,
    RetryProviderScope,
    SameProviderRetryPolicy,
)
from llm_provider_router.router import ProviderRouter, StreamFailurePolicy, StreamRestart
from llm_provider_router.scoring import ProviderScore, ScoreWeights, calculate_provider_score
from llm_provider_router.stats import ProviderStats, aggregate_stats
from llm_provider_router.storage import (
    METRICS_SCHEMA_VERSION,
    DatabaseCreation,
    DatabaseInspection,
    DatabaseMigration,
    DuckDBMetricsStore,
    ExponentialScoreWeighting,
    FlatScoreWeighting,
    LocalBackend,
    MetricsSchemaMismatchError,
    MetricsStore,
    MigrationStep,
    PostgresConfig,
    PostgresCreation,
    PostgresInspection,
    PostgresMetricsStore,
    PostgresPoolMode,
    ScoreAggregate,
    ScoreAggregateProvider,
    ScoreAggregateQuery,
    SQLiteMetricsStore,
    StorageAdministrationError,
    StorageBackupError,
    StorageBusyError,
    StorageCompatibilityError,
    StorageDependencyError,
    StorageTargetError,
    create_database,
    create_postgres_database,
    inspect_database,
    inspect_postgres_database,
    migrate_database,
    redact_postgres_url,
)
from llm_provider_router.types import (
    CallType,
    CallVariant,
    EligibilityResult,
    FilterReason,
    ProviderAttempt,
)

__all__ = [
    "ApiProtocol",
    "CallVariant",
    "CallType",
    "ConfigError",
    "DatabaseCreation",
    "DatabaseInspection",
    "DatabaseMigration",
    "DuckDBMetricsStore",
    "DuplicateCallVariantProtocolError",
    "ErrorCategory",
    "ExponentialScoreWeighting",
    "EligibilityResult",
    "FilterReason",
    "FlatScoreWeighting",
    "HealthConfig",
    "HistoryScope",
    "InvalidOperationArgumentsError",
    "LocalBackend",
    "METRICS_SCHEMA_VERSION",
    "MetricsEvent",
    "MetricsSchemaMismatchError",
    "MetricsStore",
    "MigrationStep",
    "MixedCallTypeError",
    "MissingApiKeyError",
    "ModelArgumentConflictError",
    "NoEligibleProvidersError",
    "NoProvidersConfiguredError",
    "NormalizedStream",
    "NygenRouterError",
    "Policy",
    "PostgresConfig",
    "PostgresCreation",
    "PostgresInspection",
    "PostgresMetricsStore",
    "PostgresPoolMode",
    "ProviderAttempt",
    "ProviderConfig",
    "ProviderConnectionError",
    "ProviderError",
    "ProviderHTTPError",
    "ProviderResponsesError",
    "ProviderHealthReport",
    "ProviderRouter",
    "ProviderScore",
    "ProviderSDKNotInstalledError",
    "ProviderStats",
    "ProviderStreamInterruptedError",
    "ProviderTimeoutError",
    "RoundRobinPolicy",
    "RetryContext",
    "RetryPolicy",
    "RetryProviderScope",
    "RoutingContext",
    "RouterClosedError",
    "RouterExhaustedError",
    "ScoreBasedPolicy",
    "ScoreAggregate",
    "ScoreAggregateProvider",
    "ScoreAggregateQuery",
    "ScoreWeights",
    "SQLiteMetricsStore",
    "SameProviderRetryPolicy",
    "StreamFailurePolicy",
    "StreamRestart",
    "StickyRoutingPolicy",
    "StorageAdministrationError",
    "StorageBackupError",
    "StorageBusyError",
    "StorageCompatibilityError",
    "StorageDependencyError",
    "StorageTargetError",
    "UnsupportedOperationError",
    "UnsupportedProtocolError",
    "aggregate_stats",
    "calculate_provider_score",
    "create_database",
    "create_postgres_database",
    "filter_eligible_providers",
    "inspect_database",
    "inspect_postgres_database",
    "migrate_database",
    "redact_postgres_url",
]
